# Generated by Django 4.0.4 on 2022-05-28 11:37

import uuid

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='created_by',
        ),
        migrations.AddField(
            model_name='roadmap',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='brand',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='sale_date_from',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='sale_date_to',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='nip',
            field=models.CharField(max_length=10, validators=[django.core.validators.MinLengthValidator(10)]),
        ),
        migrations.AlterField(
            model_name='client',
            name='trader',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client', to=settings.AUTH_USER_MODEL),
        ),
    ]
