# Generated by Django 4.0.4 on 2022-05-29 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_alter_client_email_alter_client_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='sale_date_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='sale_date_to',
            field=models.DateField(blank=True, null=True),
        ),
    ]
