# Generated by Django 4.0.4 on 2022-06-12 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_sale_external_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='external_id',
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='roadmap',
            name='external_id',
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
    ]
