# Generated by Django 4.0.4 on 2022-06-12 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_salemonths'),
    ]

    operations = [
        migrations.AddField(
            model_name='salemonths',
            name='sale_month_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
    ]
