# Generated by Django 4.0.4 on 2022-06-16 16:34

from django.contrib.auth.models import Group, Permission
from django.core.management.sql import emit_post_migrate_signal
from django.db import migrations
from user.permissions import (
    MANAGER_GROUP_PERMISSIONS,
    TEAMLEADER_GROUP_PERMISSIONS,
    TRADER_GROUP_PERMISSIONS,
)


def add_permissions(apps, schema_editor):
    emit_post_migrate_signal(2, False, "default")
    managers, _ = Group.objects.get_or_create(name="managers")
    for permission in MANAGER_GROUP_PERMISSIONS:
        perm_obj = Permission.objects.get(codename=permission)
        managers.permissions.add(perm_obj)
        managers.save()
    teamleaders, _ = Group.objects.get_or_create(name="teamleaders")
    for permission in TEAMLEADER_GROUP_PERMISSIONS:
        perm_obj = Permission.objects.get(codename=permission)
        teamleaders.permissions.add(perm_obj)
        teamleaders.save()
    traders, _ = Group.objects.get_or_create(name="traders")
    for permission in TRADER_GROUP_PERMISSIONS:
        perm_obj = Permission.objects.get(codename=permission)
        traders.permissions.add(perm_obj)
        traders.save()


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0009_salemonths_sale_month_amount"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="client",
            options={
                "permissions": [
                    ("can_view_only_my_clients", "Can view only my clients"),
                    ("can_create_only_my_clients", "Can create only my clients"),
                    ("can_update_only_my_clients", "Can update only my clients"),
                    ("can_delete_only_my_clients", "Can delete only my clients"),
                    ("can_view_my_group_clients", "Can view my goup clients"),
                    ("can_create_my_group_clients", "Can create my goup clients"),
                    ("can_update_my_group_clients", "Can update my goup clients"),
                    ("can_delete_my_group_clients", "Can delete my goup clients"),
                    ("can_view_department_clients", "Can view department clients"),
                    ("can_create_department_clients", "Can create department clients"),
                    ("can_update_department_clients", "Can update department clients"),
                    ("can_delete_department_clients", "Can delete department clients"),
                ]
            },
        ),
        migrations.AlterModelOptions(
            name="roadmap",
            options={
                "permissions": [
                    ("can_view_only_my_roadmaps", "Can view only my roadmaps"),
                    ("can_create_only_my_roadmaps", "Can create only my roadmaps"),
                    ("can_update_only_my_roadmaps", "Can update only my roadmaps"),
                    ("can_delete_only_my_roadmaps", "Can delete only my roadmaps"),
                    ("can_view_my_group_roadmaps", "Can view my goup roadmaps"),
                    ("can_create_my_group_roadmaps", "Can create my goup roadmaps"),
                    ("can_update_my_group_roadmaps", "Can update my goup roadmaps"),
                    ("can_delete_my_group_roadmaps", "Can delete my goup roadmaps"),
                    ("can_view_department_roadmaps", "Can view department roadmaps"),
                    (
                        "can_create_department_roadmaps",
                        "Can create department roadmaps",
                    ),
                    (
                        "can_update_department_roadmaps",
                        "Can update department roadmaps",
                    ),
                    (
                        "can_delete_department_roadmaps",
                        "Can delete department roadmaps",
                    ),
                ]
            },
        ),
        migrations.AlterModelOptions(
            name="sale",
            options={
                "permissions": [
                    ("can_view_only_my_sales", "Can view only my sales"),
                    ("can_create_only_my_sales", "Can create only my sales"),
                    ("can_update_only_my_sales", "Can update only my sales"),
                    ("can_delete_only_my_sales", "Can delete only my sales"),
                    ("can_view_my_group_sales", "Can view my goup sales"),
                    ("can_create_my_group_sales", "Can create my goup sales"),
                    ("can_update_my_group_sales", "Can update my goup sales"),
                    ("can_delete_my_group_sales", "Can delete my goup sales"),
                    ("can_view_department_sales", "Can view department sales"),
                    ("can_create_department_sales", "Can create department sales"),
                    ("can_update_department_sales", "Can update department sales"),
                    ("can_delete_department_sales", "Can delete department sales"),
                ]
            },
        ),
        migrations.RunPython(add_permissions, reverse_code=migrations.RunPython.noop),
    ]
