# Generated by Django 4.0.4 on 2022-06-16 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0010_alter_client_options_alter_roadmap_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='created_datetime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
